name: murzfeed-bot-runner

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  DETA_BASE_TOKEN: ${{ secrets.DETA_BASE_TOKEN }}
  TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}

jobs:
  runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: bahmutov/npm-install@HEAD
      - name: install dependencies
        run: yarn install
      - name: compile resources
        run: yarn compile
      - name: run bot
        run: yarn start
