name: murzfeed-bot-runner

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: egordm/gha-yarn-node-cache@v1
      - name: install dependencies
        run: yarn install
      - name: run bot
        run: yarn install
